name: Node.js Action

on:
  schedule:
    - cron: '0 */5 * * *'  # Menjalankan setiap 5 jam
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ganti dengan versi Node.js yang diinginkan

      - name: Install dependencies
        run: npm install

      - name: Run application
        run: npm start  # Atau ganti dengan perintah yang sesuai
