name: Node.js with FFmpeg Action

on:
  schedule:
    - cron: '0 */5 * * *'  # Menjalankan setiap 5 jam
  push:
    branches:
      - main
      
concurrency:
  group: update-modules
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Versi terbaru Node.js

      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: npm install

      - name: Run application
        run: npm start  # Ganti dengan perintah yang sesuai
