name: Test Push

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Create a test file
      run: echo "This is a test file." > test-file.txt

    - name: Commit and Push Changes
      run: |
        git add test-file.txt
        git commit -m "Add test file" || echo "No changes to commit"
        git push origin main  # Pastikan untuk menyebutkan branch yang sesuai
      env:
        GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
